### Python lists

In [1]:
[0.1, 0.2, 'a', 'b']

[0.1, 0.2, 'a', 'b']

### Numpy array

In [2]:
import numpy as np

np.array([0.1, 0.2, 0.3, 0.4])

array([0.1, 0.2, 0.3, 0.4])

### Pandas DataFrame

![title](pandas_df.png)

---
# <center><font color=purple>[pandas](https://pandas.pydata.org/)[docs](https://pandas.pydata.org/pandas-docs/stable/index.html)</font></center>
---

## Standard import

In [3]:
import pandas as pd

---
# <center> <font color=darkgreen>Creating a DataFrame</font></center>
---

## Create a DataFrame from a dictionary

In [4]:
df1 = pd.DataFrame({'A':[25,56,93] , 
                    'B':['str1','str2','str3']})

df1.head(20)

    A     B
0  25  str1
1  56  str2
2  93  str3

### Change the index: [`set_index()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html)

The default index is a list of integers. Use `set_index()` to assign a column to be the index.

In [5]:
df2 = df1.set_index('A')
df2

       B
A
25  str1
56  str2
93  str3

## Load data from an external source

In [6]:
# pd.read_

## Load a DataFrame from a file

In [7]:
CH = pd.read_csv('../data/celebrity-heights.csv')
CH.head(20)

,id,firstname,midname,lastname,fullname,ftin,feet,inches,meters,gender
0,1,Verne,NaN,Troyer,Verne Troyer,2ft 8in,2,8.0,0.81280,M
1,8,Herve,NaN,Villechaize,Herve Villechaize,3ft 10in,3,10.0,1.16840,M
2,9,David,NaN,Rappaport,David Rappaport,3ft 11in,3,11.0,1.19380,M
3,2,Tony,NaN,Cox,Tony Cox,3ft 6in,3,6.0,1.06680,M
4,3,Warwick,NaN,Davis,Warwick Davis,3ft 6in,3,6.0,1.06680,M
5,4,Phil,NaN,Fondacaro,Phil Fondacaro,3ft 6in,3,6.0,1.06680,M
6,5,Michael,J,Anderson,Michael J Anderson,3ft 7in,3,7.0,1.09220,M
7,6,Kenny,NaN,Baker,Kenny Baker,3ft 8in,3,8.0,1.11760,M
8,7,Billy,NaN,Barty,Billy Barty,3ft 9in,3,9.0,1.14300,M
9,10,Kiran,NaN,Shah,Kiran Shah,4ft 1.7in,4,1.7,1.26238,F
10,17,Nikki,NaN,Blonsky,Nikki Blonsky,4ft 10in,4,10.0,1.47320,F
11,18,Kristin,NaN,Chenoweth,Kristin Chenoweth,4ft 10in,4,10.0,1.47320,F
12,19,Danny,NaN,DeVito,Danny DeVito,4ft 10in,4,10.0,1.47320,M
13,20,Kelly,NaN,Stables,Kelly Stables,4ft 10in,4,10.0,1.47320,F
14,32,Jeillo,NaN,Edwards,Jeillo Edwards,4ft 11.5in,4,11.5,1.51130,NaN
15,33,Lorena,NaN,Gale,Lorena Gale,4ft 11.5in,4,11.5,1.51130,F
16,34,Lisa,NaN,Origlasso,Lisa Origlasso,4ft 11.5in,4,11.5,1.51130,F
17,35,Elaine,NaN,Paige,Elaine Paige,4ft 11.5in,4,11.5,1.51130,F
18,36,Jada,Pinkett,Smith,Jada Pinkett Smith,4ft 11.5in,4,11.5,1.51130,F
19,37,Marissa,Jaret,Winokur,Marissa Jaret Winokur,4ft 11.5in,4,11.5,1.51130,F

In [8]:
CH.iloc[[1,5,11,12],[1,3,5,6,7]]

   firstname     lastname      ftin  feet  inches
1      Herve  Villechaize  3ft 10in     3    10.0
5       Phil    Fondacaro   3ft 6in     3     6.0
11   Kristin    Chenoweth  4ft 10in     4    10.0
12     Danny       DeVito  4ft 10in     4    10.0

In [9]:
CH.set_index('fullname', inplace=True)
CH.head(8)

,id,firstname,midname,lastname,ftin,feet,inches,meters,gender
fullname,,,,,,,,,
Verne Troyer,1,Verne,NaN,Troyer,2ft 8in,2,8.0,0.8128,M
Herve Villechaize,8,Herve,NaN,Villechaize,3ft 10in,3,10.0,1.1684,M
David Rappaport,9,David,NaN,Rappaport,3ft 11in,3,11.0,1.1938,M
Tony Cox,2,Tony,NaN,Cox,3ft 6in,3,6.0,1.0668,M
Warwick Davis,3,Warwick,NaN,Davis,3ft 6in,3,6.0,1.0668,M
Phil Fondacaro,4,Phil,NaN,Fondacaro,3ft 6in,3,6.0,1.0668,M
Michael J Anderson,5,Michael,J,Anderson,3ft 7in,3,7.0,1.0922,M
Kenny Baker,6,Kenny,NaN,Baker,3ft 8in,3,8.0,1.1176,M

## Load a DataFrame from online data

+ We will load data on eductional attainment and personal income from the [California Open Data](https://data.ca.gov/dataset/ca-educational-attainment-personal-income/resource/26201f19-4469-4311-a819-bbbd3e557eda) portal. 
+ Go to the website, copy the URL and enter it below.

In [19]:
hdr = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
    'Accept-Encoding': 'none',
    'Accept-Language': 'en-US,en;q=0.8',
    'Connection': 'keep-alive'
}

url = "https://data.ca.gov/dataset/cea8cd18-9d21-4676-85de-d504ee2d4aab/resource/26201f19-4469-4311-a819-bbbd3e557eda/download/ca-educational-attainment-personal-income-2008-2014.csv"

url1 = "https://waylonwalker.com/cars.csv"

table = pd.read_csv(url, storage_options=hdr)

HTTPError: HTTP Error 403: Forbidden

In [18]:
table.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [ ]:
table.describe()

## DataFrame summaries
+ [info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html#): Column data types.
+ [describe()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html#): Summary statistics for numerical columns
+ [head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html), [tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail) : Show first or last few rows of a table

In [ ]:
table.tail(10)

---
# <center> <font color=darkgreen>Selecting data</font>  </center>
---

There are three basic ways to select data from a DataFrame. 

+ `[]`: Bracket selection
+ `.loc[]` : Label-based selection
+ `.iloc[]` : Integer-based selection

## `[]` Bracket selection

Syntax: `X[selector]`
+ To select columns the `selector` can be
    + A column label (string)
    + A list of column labels (list of strings)
+ To select rows the `selector` can be
    + A slice
    + A boolean mask

### Select a single column (string)

In [ ]:
CH['firstname']

### Select multiple columns (list of strings)

In [ ]:
CH[['firstname', 'lastname']]

In [ ]:
type(CH[['firstname','lastname']])

### Select rows with slice indexing
[Slice indexing](https://docs.python.org/3/tutorial/introduction.html), in which you specify a start index, a stop index, and a step, works in the same way in Pandas as it does for regaular Python lists.

In [ ]:
CH[2:]

### Select rows with a boolean mask

You can use a boolean list or a boolean Series as a mask for filtering rows.

In [ ]:
CH.loc[CH['midname'] == 'J', 'lastname']

## `loc[]` : Label-based selection

Syntax: `X.loc[rowselector,columnselector]` (`columnselector` is optional)
 
`rowselector` can be
+ An index (integer, string, date, etc.)
+ A list of indexes.
+ A slice (only if the index is integer-based)
+ A boolean mask

`columnselector` can be 
+ A string label. 
+ A list of strings labels.

### `.loc` can do (almost) anything `[]` can do

+ Except: .loc(slice) only works if the index is the integer-based default index. 
+ For column selection, use `.loc[:,columnselector]`

In [ ]:
CH.loc[:,'gender']

### Example: Select multiple rows and columns

In [ ]:
CH.loc[CH['gender'] == 'M', ['firstname','meters','ftin']]

### Example: Boolean masking

In [ ]:
CH.loc[CH.index<10,['firstname','lastname','gender','meters']]

## `iloc[]`:  Integer-based selection
    
Syntax: `iloc[rowselector,columnselector]` (`columnselector` is optional)
 
`rowselector` and `columnselector` can be
+ An integer or list of integers
+ A slice

    
### Examples

In [ ]:
CH.iloc[:10,[1,2]]

- First item
- Second item
- Third item
    - Indented item
    - Indented item
- Fourth item